org: halokesproject
app: serverless-testcoursedev-identity
service: serverless-testcoursedev-identity
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
